# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250)),
                ('image_category', models.CharField(max_length=250)),
                ('image_description', models.CharField(max_length=1000)),
                ('image_file', models.ImageField(upload_to=image.models.generate_filename)),
                ('image_tags', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
