# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=250, unique=True)),
                ('favouriteList', models.CharField(max_length=2000)),
            ],
        ),
    ]
